const prefix = 'Landing'

export const SAVE_TRAININGS_SUCCESS = prefix + '/SAVE_TRAININGS_SUCCESS'
export const SAVE_TRAININGS_FAILURE = prefix + '/SAVE_TRAININGS_FAILURE'

export const FETCH_TRAININGS_SUCCESS = prefix + '/FETCH_TRAININGS_SUCCESS'
export const FETCH_TRAININGS_FAILURE = prefix + '/FETCH_TRAININGS_FAILURE'

export const ADD_DISPLAYED_MONTH = prefix + '/ADD_DISPLAYED_MONTH'

export const TOGGLE_DONATE_DIALOG = prefix + '/TOGGLE_DONATE_DIALOG'
export const TOGGLE_RATE_DIALOG = prefix + '/TOGGLE_RATE_DIALOG'
