const prefix = 'Landing'

export const SAVE_TRAININGS_SUCCESS = prefix + '/SAVE_TRAININGS_SUCCESS'
export const SAVE_TRAININGS_FAILURE = prefix + '/SAVE_TRAININGS_FAILURE'

export const FETCH_TRAININGS_SUCCESS = prefix + '/FETCH_TRAININGS_SUCCESS'
export const FETCH_TRAININGS_FAILURE = prefix + '/FETCH_TRAININGS_FAILURE'
